<<<<<<< HEAD:pekan1/Tugas1_2611533011.py
print("             /\\")
print("            /  \\")
print("           /    \\")
print("          /      \\")
print("         /   😎   \\")
print("        /          \\")
print("       /            \\")
print("      /______________\\")
print("      |              |")
print("      |     SEHAT    |")
print("      |    ANAK IF   |")
print("      |              |")
print("      |              |")
print("     /|              |\\")
print("    /_|______________|_\\")
print("      /              \\")
print("     /                \\")
print("    /__________________\\")
print("         ||      ||")
print("         ||      ||")
print("        🔥🔥    🔥🔥")
print("       🔥🔥🔥  🔥🔥🔥")
=======
print("             /\\")
print("            /  \\")
print("           /    \\")
print("          /      \\")
print("         /   😎   \\")
print("        /          \\")
print("       /            \\")
print("      /______________\\")
print("      |              |")
print("      |     SEHAT    |")
print("      |    ANAK IF   |")
print("      |              |")
print("      |              |")
print("     /|              |\\")
print("    /_|______________|_\\")
print("      /              \\")
print("     /                \\")
print("    /__________________\\")
print("         ||      ||")
print("         ||      ||")
print("        🔥🔥    🔥🔥")
print("       🔥🔥🔥  🔥🔥🔥")
>>>>>>> f031df08c9810a6478b7a367397853c83a6e7bda:pekan 1/Tugas1_2611533011.py
print("      🔥🔥🔥🔥🔥🔥🔥🔥")